### ISSUE TITLE
LibIndy for android - indy_prover_store_credential error

### ISSUE THREAD

**Issue by Veerendra-b** [hyperledger/indy-sdk#2429] opened 2021-10-01 07:42 UTC
Storing of the credentials in the mobile wallet for android, using libindy.so (https://repo.sovrin.org/android/libindy/stable/1.16.0/), is failing.
We see the below error when we call the java wrapper method - proverStoreCredential which internally invokes the indy_prover_store_credential on libindy.

`error::java.util.concurrent.ExecutionException: org.hyperledger.indy.sdk.InvalidStructureException: A value being processed is not valid.`

The libindy logs are not specific about which structure is invalid, while there are 5 input params  in the method signature.

Any idea what could be causing this?

**Comment by zerjioang** [comment] 2021-11-05 12:35
@Veerendra-b if the problem is finally solved, could you close the issue?

**Closed** 2022-04-05 06:49 UTC
