### ISSUE TITLE
Multisignature submission of NYM tx rejected. Bug?

### ISSUE THREAD

**Issue by zerjioang** [hyperledger/indy-sdk#2401] opened 2021-06-22 11:10 UTC
## Goal

I want to register a DID + VERKEY in the ledger without being ENDORSER nor accepting TAA. To do so, I want to delegate submission on a known endorser. In following example, known endorser is a bootstrapped steward on test network

## Error description

Im triying to submit a NYM tx in order to register a DID+VERKEY in the ledger as part of a project. I setup a local development network with 4 different nodes distributed in 4 vm, so that each vm has a node. 

I successfully tried to submit and register a DID using bootstrapped steward DID (with seed `000000000000000000000000Steward1`).

However, when I try to submit a NYM tx to register a DID as new non-bootstrapped user I get an error. The process im following is:

1. Create steward user with did `000000000000000000000000Steward1`.  Lets call it **steward** user, which give me: 

```bash
DID: Th7MpTaRZVRYnPiabds81Y
VERKEY: FYmoFw55GeQH7SRFa37dkx1d2dZ3zUF8ckg7wmL7ofN4
```

2. Create a random DID from random seed. Lets call it **demo** user. For this example, I choose the seed `546fdgjh5d65g41gfd54j4h5df46df5g``which creates:

```bash
DID: 14YaxrmCve7TYNKdjs6VaJ
VERKEY: 12w3xyoUjZqDQzhv8KszyEc5zn8P8iV7NF57jHGyWHdG
```

2.1: Both **steward** and **demo** onboard successfully using previous dids so that both DIDs are registered in the ledger.
2.2 The new did user **demo** wants to register is

```bash
Did:    "JWMDX3bMnRF6tu1j2g2a3L",
Verkey: "AYQApRjgZhFMYnccBNjA35Mn9Xzvp6B6G9RHBeSSBm6w"
```

3. Now with **demo** user, I build a NYM transaction and locally sign it. The result of that operation is.

```json
{
	"endorser": "Th7MpTaRZVRYnPiabds81Y",
	"identifier": "14YaxrmCve7TYNKdjs6VaJ",
	"operation": {
		"dest": "JWMDX3bMnRF6tu1j2g2a3L",
		"role": "101",
		"type": "1",
		"verkey": "AYQApRjgZhFMYnccBNjA35Mn9Xzvp6B6G9RHBeSSBm6w"
	},
	"protocolVersion": 2,
	"reqId": 1624359312147463722,
	"signature": "VzPnhSXQuFeNgEnkkAwqMKcps5Z1DpqThK2vwXCxLAXZLd79gnTNYz58cTyRS2Kuiv8Lv2BPtcBYECon518oaZ6"
}
```

So far so good.
5. Now I send this payload to **steward** user (for simplicity, lets forget about how I send it to steward, and whether is encrypted or not). The point is, **steward** gets the NYM tx data, and signs the transaction using multisig method call `C.indy_multiSignRequest(wh, submitterDid, request, cb)`. The result of multisigning is:

```json
{
	"endorser": "Th7MpTaRZVRYnPiabds81Y",
	"identifier": "14YaxrmCve7TYNKdjs6VaJ",
	"operation": {
		"dest": "JWMDX3bMnRF6tu1j2g2a3L",
		"role": "101",
		"type": "1",
		"verkey": "AYQApRjgZhFMYnccBNjA35Mn9Xzvp6B6G9RHBeSSBm6w"
	},
	"protocolVersion": 2,
	"reqId": 1624359312147463722,
	"signatures": {
		"14YaxrmCve7TYNKdjs6VaJ": "VzPnhSXQuFeNgEnkkAwqMKcps5Z1DpqThK2vwXCxLAXZLd79gnTNYz58cTyRS2Kuiv8Lv2BPtcBYECon518oaZ6",
		"Th7MpTaRZVRYnPiabds81Y": "55fJbUGYro2S9y5yHHbb3h4yUbAdVhyy1YK9AwLXbu4fVsBtQv7ipZ1mZz5YHX2Rx44H7hUTL9D4sRrGtWKVaDo1"
	}
}
```

As final step, the **steward** connects with the pool in order to submit the transaction using the method `C.indy_submitRequest(poolHandle, request, cb)` and the response from the ledger is:

```json
{
	"identifier": "14YaxrmCve7TYNKdjs6VaJ",
	"op": "REJECT",
	"reqId": 1624359312147463722,
	"reason": "client request invalid: UnauthorizedClientRequest(\"Rule for this action is: 1 STEWARD signature is required OR 1 TRUSTEE signature is required\\nFailed checks:\\nConstraint: 1 STEWARD signature is required, Error: Endorser must have one of the following roles: {'ENDORSER'}\\nConstraint: 1 TRUSTEE signature is required, Error: Not enough TRUSTEE signatures\",)"
}
```

Why is this error happening if the request is signed by 1 STEWARD? Arent STEWARDs valid ENDORSERs? Am I missing something else?

## Expected result

NYM tx successfully registered in the ledger

## My environment:

* indy-sdk
* libindy v1.15.0
* Linux 5.3.0-59-generic #53~18.04.1-Ubuntu  x86_64 x86_64 x86_64 GNU/Linux

**Comment by WadeBarnes** [comment] 2021-06-22 12:03
Looks like you don't have any signatures from a TRUSTEE; `1 TRUSTEE signature is required, Error: Not enough TRUSTEE signatures`

**Comment by WadeBarnes** [comment] 2021-06-22 12:08
To which network are you writing the transaction?  What are the roles associated with the first two DIDs?

**Comment by zerjioang** [comment] 2021-06-22 12:18
@WadeBarnes im working with a network based on default indy test network, the one is bootstrap automatically, so that as far as I know this are the roles

| Did                    | Role    | Seed                             | Ledger registered?           |
|------------------------|---------|----------------------------------|------------------------------|
| Th7MpTaRZVRYnPiabds81Y | STEWARD | 000000000000000000000000Steward1 | Yes (bootstrapped)           |
| 14YaxrmCve7TYNKdjs6VaJ | NONE    | 546fdgjh5d65g41gfd54j4h5df46df5g | Yes (via steward onboarding) |
| JWMDX3bMnRF6tu1j2g2a3L | NONE    |                                  | No                           |

My development environment is based on image https://github.com/hyperledger/indy-sdk/blob/master/ci/indy-pool.dockerfile in which I removed supervisord and setup indy-node as main docker container process.

**Comment by WadeBarnes** [comment] 2021-06-22 14:17
How was `Th7MpTaRZVRYnPiabds81Y` registered with the network, what was the `role` defined in the transaction?

You can confirm the role by connecting to your network via the `indy-cli` and running `ledger get-nym did=Th7MpTaRZVRYnPiabds81Y`.  The response will confirm role assigned to the DID.

**Comment by WadeBarnes** [comment] 2021-06-22 14:19
@zerjioang, For development, you may find `von-network` easier to use.  It has a built in ledger browser, and has a fully containerized `indy-cli` environment you can use to connect to and query any `indy-node` based network.

**Comment by zerjioang** [comment] 2021-06-23 07:16
@WadeBarnes after running `ledger get-nym did=Th7MpTaRZVRYnPiabds81Y` the response I get using indy cli tool is

```bash
mywallet:indy> pool connect sandbox
Pool "sandbox" has been connected
pool(sandbox):mywallet:indy> ledger get-nym did=Th7MpTaRZVRYnPiabds81Y
Following NYM has been received.
Metadata:
+------------------------+-----------------+---------------------+------------------+
| Identifier             | Sequence Number | Request ID          | Transaction time |
+------------------------+-----------------+---------------------+------------------+
| LibindyDid111111111111 | 2               | 1624432436709783274 | -                |
+------------------------+-----------------+---------------------+------------------+
Data:
+------------------------+------------------------+-------------------------+---------+
| Identifier             | Dest                   | Verkey                  | Role    |
+------------------------+------------------------+-------------------------+---------+
| V4SGRU86Z58d6TV7PBUe6f | Th7MpTaRZVRYnPiabds81Y | ~7TYfekw4GUagBnBVCqPjiC | STEWARD |
+------------------------+------------------------+-------------------------+---------+
pool(sandbox):mywallet:indy> 
```

so indy-cli also confirms that did `Th7MpTaRZVRYnPiabds81Y` has steward role. Right?

**Comment by WadeBarnes** [comment] 2021-06-24 13:25
Using the indy-cli run `ledger get-auth-rule` to check the auth-rules for your network.  I think the error may be misleading.  I think you may require a Trustee signature to add an Endorser (role: 101) to the ledger.  Also ensure, your indy-cli's `sandbox` pool is connected to the same leger as your code (in the off chance it's not).

**Comment by lynnbendixsen** [comment] 2021-06-24 18:13
The bottom line here is the answer to your question "Aren't STEWARDs valid ENDORSERs?" No, they are not.
A while ago the roles were reorganized in a way that Stewards have very little privileges on the network by default and they cannot, as far as I know, be considered an ENDORSER without a code change.  Stewards are now able to manage their own node and see network maintenance info and that is about all.  By default a Steward can add an Endorser to the network, but that privilege is removed on the networks I manage and setup as that is not the intended use of a Steward anymore.
I was able to replicate your issue above using just the indy-cli. To prove that it will work as mentioned in this comment, I then changed the "endorser" to be a valid endorser on the network and got a signature from the Steward, the Endorser, and the Author (unprivileged 'Demo" user), and the transaction was successfully written to the Indicio DemoNet (see results in seq numbers 12-4 here if desired: https://indyscan.indiciotech.io/home/INDICIO_DEMONET2).  This was all done using the default auth-rules that indy ships with.

To raise awareness, I will also mention that the premise for what you are trying to do here seems a bit odd to me.  While I don't doubt that a valid use case could exist for a non-privileged user to be able to add an Endorser to your network (with proper authorization/signatures), it makes more sense for a Trustee (or a steward if you like) to approve and add a new Endorser directly to the network. Just send the DID and Verkey to the Trustee and ask them to add the Endorser. On the MainNets (production networks) that I have helped manage, the Endorsers must sign an Endorser agreement and be approved by a committee before they can be an Endorser, then a Trustee must run the transaction that sends their DID to the ledger if they are approved.  For test ledgers we have a selfserve app that adds endorsers "for free" to allow for organizations to try things out freely on those trial ledgers.

**Comment by zerjioang** [comment] 2021-06-28 09:00
@WadeBarnes @lynnbendixsen thanks for your feedback. I will do the same process as described using a trustee and report the results here. However, if rules have changed, I encounter confusing the message

```bash
Rule for this action is: 1 STEWARD signature is required OR 1 TRUSTEE signature is required
```

so if stewards are not valid endorsers anymore, the error message should be updated.

**Comment by WadeBarnes** [comment] 2021-06-28 16:00
@zerjioang, That's why I asked you to confirm the Auth Rules of your particular network.  Typically those messages are based on the rules configured for a specific ledger.  It obviously makes it very confusing when it's telling you either a `STEWARD` signature **OR** a `TRUSTEE` signature is required, when in fact it requires a `TRUSTEE` signature and will not accept the `STEWARD` signature.

**Comment by lynnbendixsen** [comment] 2021-06-30 21:41
@zerjioang The default Auth rules (which you are likely using) were the cause for the error message quoted in your latest message, so the error message is "accurate", but still confusing.  A Steward or a Trustee must sign the txn that you tried to send.  It is a completely separate issue that since you were also trying to send the txn to the ledger using an unprivileged DID (or "Author"), that an Endorser DID and signature is ALSO required. I am not a fan of the way all of the "error" messages a strung together, but the piece about the "Steward role is not an Endorser" issue is "Error: Endorser must have one of the following roles: {'ENDORSER'}"  Does that make more sense?   
To be clear, I agree that the error message is confusing and could be greatly improved upon.  Here I am just trying to help you understand the various pieces of it for future reference.  Hope it helps!

**Comment by zerjioang** [comment] 2021-07-07 10:03
While I reassemble my example to work with proposed new configurations, I  just let you know I was following the proposed method of https://github.com/hyperledger/indy-node/blob/master/design/transaction_endorser.md, just in case someone wants to get the detais of tx endorsement design/methodology.

**Closed** 2024-02-05 16:16 UTC
Labels: wont-address-project-depreciated
